# Generated by Django 2.2.3 on 2019-07-29 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('email', models.CharField(max_length=100)),
                ('cinic', models.IntegerField(max_length=13)),
                ('bank_details', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=1000)),
            ],
        ),
    ]
