# Generated by Django 2.2.3 on 2019-07-29 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='cinic',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(13)]),
        ),
    ]
