# Generated by Django 2.2.3 on 2019-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20190729_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='name',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
