# Generated by Django 2.2.3 on 2019-07-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20190729_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
