# Generated by Django 2.2.3 on 2019-07-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20190729_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='last_name',
        ),
    ]
