# Generated by Django 2.2.3 on 2019-07-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_employeedetails_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='cinic',
            new_name='cnic',
        ),
    ]
