# Generated by Django 2.2.3 on 2019-07-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_auto_20190729_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='employee_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
