# Generated by Django 2.2.3 on 2019-07-30 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_employeedetails_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField(default=datetime.date)),
                ('email', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=13, null=True)),
                ('cnic', models.CharField(max_length=13)),
                ('bank_details', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='employee_id',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='cnic',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employeedetails',
            name='mobile',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.EmployeeHeader'),
        ),
    ]
