# Generated by Django 2.2.3 on 2019-08-01 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20190730_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='join_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
