# Generated by Django 2.2.3 on 2019-08-01 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_auto_20190801_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='header_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeHeader'),
        ),
    ]
