# Generated by Django 2.2.3 on 2019-08-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_auto_20190801_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='join_date',
            field=models.DateField(blank=True),
        ),
    ]
