# Generated by Django 2.2.3 on 2019-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_auto_20190801_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='salary',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
